<?php
/**
 * @link https://wmd.hr/
 * @copyright Copyright (c) WMD d.o.o.
 * @license MIT
 */

namespace wmd\designfield\services;

use Craft;
use InvalidArgumentException;
use wmd\designfield\fields\Design;
use wmd\designfield\helpers\AgentBrief;
use wmd\designfield\helpers\FieldShapes;
use wmd\designfield\helpers\MigrationPlan;
use wmd\designfield\helpers\Schema;
use wmd\designfield\helpers\TidyRows;
use wmd\designfield\Plugin;
use yii\base\Component;

/**
 * The "Tidy up" tab's data: option fields on entry types, their config, the agent brief.
 *
 * @author WMD
 * @since 1.0.0
 */
class Tidy extends Component
{
    // Public Methods
    // =========================================================================

    /**
     * @return list<array{type:string,typeName:string,movable:bool,reason:string,fields:list<array{field:string,name:string,kind:string,group:string,status:string,note:string,read:bool}>}>
     * @throws InvalidArgumentException when the configuration does not build
     *
     * @author WMD
     * @since 1.0.0
     */
    public function rows(): array
    {
        $plugin = Plugin::getInstance();
        $importer = $plugin->getImporter();
        $registry = $plugin->getGroups()->getRegistry();
        $fields = [];
        $import = $importer->fromFields();
        // fromFields() leaves out pairs the registry already maps; the rows suggest them too.
        $import['fieldMap'] += $registry->fieldMap;
        $profiles = $registry->profileNames();

        foreach (Craft::$app->getEntries()->getAllEntryTypes() as $type) {
            $layoutHandles = array_map(static fn($f) => $f->handle, $type->getFieldLayout()->getCustomFields());
            // What adopt would move, built the way Converter::adopt() builds it.
            $planned = in_array($type->handle, $profiles, true)
                ? MigrationPlan::build($layoutHandles, $registry->groupsFor([$type->handle]), $type->handle, $registry->fieldMap, false)->fields
                : [];

            foreach ($type->getFieldLayout()->getCustomFields() as $field) {
                if ($field instanceof Design) {
                    continue;
                }
                if ($field->handle === $type->handle . 'Variant') {
                    $import['fieldMap'][$field->handle] = 'variant';
                }
                $shape = $importer->describe($field);
                if (FieldShapes::group($shape) === null) {
                    continue;
                }
                $fields[] = ['type' => $type->handle, 'typeName' => $type->name, 'field' => $field->handle, 'name' => (string)$field->name, 'kind' => FieldShapes::kind($shape), 'planned' => $planned[$field->handle] ?? null];
            }
        }

        $byType = [];
        foreach ($fields as $field) {
            $byType[$field['type']][] = $field['field'];
        }
        $read = $plugin->getTemplateChecker()->fieldsRead($byType);
        foreach ($fields as $i => $field) {
            $fields[$i]['read'] = in_array($field['field'], $read[$field['type']] ?? [], true);
        }

        return TidyRows::build($fields, $import, $profiles);
    }

    /**
     * The config `design-field/import` would write for one block type, as PHP.
     *
     * @param string $type
     * @return string
     * @throws InvalidArgumentException when the configuration does not build
     *
     * @author WMD
     * @since 1.0.0
     */
    public function configFor(string $type): string
    {
        $importer = Plugin::getInstance()->getImporter();
        $config = $importer->fromFields([], [], [$type]);
        unset($config['skipped']);

        return $importer->toPhp($config, "Generated by the Design Field \"Tidy up\" tab for $type.\n" . (Plugin::getInstance()->getSettings()->isOverridden() ? "Merge into config/design-field.php." : "Add these in the plugin settings' Configuration tables: a config file would override them."));
    }

    /**
     * The Design field a block type's options move into: the one in its layout, else the
     * only Design field on the site; null when there is none or more than one to choose from.
     *
     * @param string $type Entry type handle
     * @return ?string
     *
     * @author WMD
     * @since 1.0.0
     */
    public function designFieldFor(string $type): ?string
    {
        foreach (Craft::$app->getEntries()->getEntryTypeByHandle($type)?->getFieldLayout()->getCustomFields() ?? [] as $field) {
            if ($field instanceof Design) {
                return $field->handle;
            }
        }
        $all = array_values(array_filter(Craft::$app->getFields()->getAllFields(), static fn($field) => $field instanceof Design));

        return count($all) === 1 ? $all[0]->handle : null;
    }

    /**
     * @param string $stack 'twig' or 'graphql'
     * @return string
     * @throws InvalidArgumentException when the configuration does not build
     *
     * @author WMD
     * @since 1.0.0
     */
    public function brief(string $stack): string
    {
        $plugin = Plugin::getInstance();
        $registry = $plugin->getGroups()->getRegistry();

        return AgentBrief::build($this->rows(), Schema::build($registry), $plugin->getTemplateChecker()->check(), $stack, $plugin->getSettings()->isOverridden());
    }
}
