<?php
/**
 * @link https://wmd.hr/
 * @copyright Copyright (c) WMD d.o.o.
 * @license MIT
 */

namespace wmd\designfield\helpers;

/**
 * The option model as data, for agents, MCP tools and CI: every block's options with
 * their handle, label, look, default, section and choices, plus its presets and how
 * templates read them. As JSON, or as a compact markdown reference that can live in
 * an AGENTS.md between markers (inject()).
 *
 * Craft-free: built from the registry.
 *
 * @author WMD
 * @since 1.0.0
 */
class Schema
{
    // Const Properties
    // =========================================================================

    public const START = '<!-- design-field:start -->';
    public const END = '<!-- design-field:end -->';

    // Public Methods
    // =========================================================================

    /**
     * @param Registry $registry
     * @param array<string,string> $labels Profile => readable name (entry type name)
     * @return array{reading:array<string,string>,profiles:array<string,array{label:string,options:list<array{handle:string,label:string,look:string,default:string,section:string,choices:list<array{key:string,label:string}>}>,presets:list<array{label:string,values:array<string,string>}>}>}
     *
     * @author WMD
     * @since 1.0.0
     */
    public static function build(Registry $registry, array $labels = []): array
    {
        $profiles = [];

        foreach ($registry->profiles as $name => $groups) {
            $options = [];
            foreach ($groups as $handle => $group) {
                $choices = [];
                foreach ($group->options as $key => $option) {
                    $choices[] = ['key' => (string)$key, 'label' => $option['label']];
                }
                $options[] = [
                    'handle' => (string)$handle,
                    'label' => $group->label,
                    'look' => StyleChoices::value(['input' => $group->input, 'iconsOnly' => $group->iconsOnly, 'textOnly' => $group->textOnly]),
                    'default' => $group->default,
                    'section' => $group->section,
                    'choices' => $choices,
                ];
            }

            $profiles[(string)$name] = [
                'label' => $labels[$name] ?? (string)$name,
                'options' => $options,
                'presets' => $registry->presetsFor((string)$name, $groups),
            ];
        }

        return [
            'reading' => [
                'get' => '{% set design = craft.designField.of(block) %}',
                'key' => '{{ design.tone.key }}',
                'part' => "{{ design.tone.get('bg') }}",
                'classes' => "{{ design.classes('tone', 'spacing') }}",
                'has' => "{% if design.has('variant') %}…{% endif %}",
            ],
            'profiles' => $profiles,
        ];
    }

    /**
     * A compact reference: how to read options, then one list per block.
     *
     * @param array{reading:array<string,string>,profiles:array<string,array<string,mixed>>} $schema build()
     * @return string
     *
     * @author WMD
     * @since 1.0.0
     */
    public static function markdown(array $schema): string
    {
        $lines = [
            '## Design Field options',
            '',
            'Generated by `craft design-field/schema`; do not edit by hand. Blocks read their design options in Twig:',
            '',
            '```twig',
            $schema['reading']['get'],
            $schema['reading']['key'] . '              {# the picked key #}',
            $schema['reading']['part'] . '      {# one part of its value #}',
            $schema['reading']['classes'],
            $schema['reading']['has'],
            '```',
            '',
            'Keys, not labels, are stored and compared. `*` is every block without a profile of its own.',
        ];

        $line = static function(array $option): string {
            $keys = implode(', ', array_map(static fn(array $choice) => "`{$choice['key']}`", $option['choices']));
            return "- `{$option['handle']}` {$option['label']} — {$option['look']}, default `{$option['default']}`: $keys";
        };

        // An option exactly the same on two or more blocks is listed once, under Shared options.
        $uses = [];
        foreach ($schema['profiles'] as $profile) {
            foreach ($profile['options'] as $option) {
                $uses[$line($option)] = ($uses[$line($option)] ?? 0) + 1;
            }
        }
        $shared = array_keys(array_filter($uses, static fn(int $count) => $count > 1));
        if ($shared !== []) {
            sort($shared);
            $lines[] = '';
            $lines[] = '### Shared options';
            $lines[] = '';
            $lines[] = 'The same on every block that lists them under "Shared".';
            $lines[] = '';
            array_push($lines, ...$shared);
        }

        foreach ($schema['profiles'] as $name => $profile) {
            $lines[] = '';
            $lines[] = $profile['label'] === $name ? "### `$name`" : "### {$profile['label']} (`$name`)";
            $common = [];
            foreach ($profile['options'] as $option) {
                if (in_array($line($option), $shared, true)) {
                    $common[] = "`{$option['handle']}`";
                    continue;
                }
                $lines[] = $line($option);
            }
            if ($common !== []) {
                $lines[] = 'Shared: ' . implode(', ', $common);
            }
            if ($profile['presets'] !== []) {
                $lines[] = 'Presets: ' . implode(', ', array_column($profile['presets'], 'label'));
            }
        }

        return implode("\n", $lines);
    }

    /**
     * Puts a section into a file's text between the markers: replaces what is between
     * them, or appends the marked section when there are none. The rest stays as is.
     *
     * @param string $file Current file text ('' for a new file)
     * @param string $section
     * @return string
     *
     * @author WMD
     * @since 1.0.0
     */
    public static function inject(string $file, string $section): string
    {
        $block = self::START . "\n" . $section . "\n" . self::END;
        $start = strpos($file, self::START);
        $end = $start === false ? false : strpos($file, self::END, $start);

        if ($start !== false && $end !== false) {
            return substr($file, 0, $start) . $block . substr($file, $end + strlen(self::END));
        }

        return ($file === '' ? '' : rtrim($file, "\n") . "\n\n") . $block . "\n";
    }
}
